from pycommerce_app.models import Category, Product

catSoap = Category.objects.create(name="Soap")
catShampoo = Category.objects.create(name="Shampoo")
catOil = Category.objects.create(name="Oil")

catSoap = Category.objects.get(id=1)
catShampoo = Category.objects.get(id=2)
catOil = Category.objects.get(id=3)


product1 = Product.objects.create(title="Amber Liquid Hand Soap", image_url="amber", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product2 = Product.objects.create(title="Antique Touch Liquid Hand Soap", image_url="antique-touch", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product3 = Product.objects.create(title="Dance of Flowers Liquid Hand Soap", image_url="dance_of_flowers", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product4 = Product.objects.create(title="Lila Bella Liquid Hand Soap", image_url="lila-bella", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product5 = Product.objects.create(title="Love Liquid Hand Soap", image_url="love", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product6 = Product.objects.create(title="Musk Liquid Hand Soap", image_url="musk", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product7 = Product.objects.create(title="Mystic Flowers Liquid Hand Soap", image_url="mystic_flowers", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product8 = Product.objects.create(title="Olive oil", image_url="olive_oil", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")
product9 = Product.objects.create(title="Oud Liquid Hand Soap", image_url="oud", price=2, inventory=1000,  quantity_sold=0, desc="Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, minus quo. Ducimus officiis sint error explicabo consequatur iusto tempore officia nam illum laudantium accusamus modi aliquam saepe, culpa magnam rem?")

catSoap.products.add(product1)
catSoap.products.add(product2)
catSoap.products.add(product3)
catSoap.products.add(product4)

catOil.products.add(product8)

catShampoo.products.add(product5)
catShampoo.products.add(product6)
catShampoo.products.add(product7)
catShampoo.products.add(product9)

catSoap.save()
catShampoo.save()
catOil.save()
