# Generated by Django 2.2.4 on 2020-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
    ]
